
spring :

#  datasource :
#    jndi-name : java:comp/env/jdbc/watchyourstocks
#    url : jdbc:h2:tcp://localhost/~/app-home/watchyourstocks/h2

  mail :
    host : smtp-pulse.com
    port : 2525
    username : vteial@gmail.com
    password : pdcsGDPk9M
