info :
  app :
    name : watchyourstocks
    description : Watch Your Stocks
    version : 1.0.0

  profiles :
    active : prd

server :
  port : 9021
  #sessionTimeout : 30

#management :
#  port : 9022
#  context-path : /_admin
#  security :
#    role : SUPERUSER
#    user :
#      name : admin
#      password : secret

spring :
  application :
    name : Watch Your Stocks

  boot :
    admin :
      url : http://localhost:9011

  profiles :
    active : prd

#  data
#    rest
#      basePath : /api

  datasource :
    driverClassName: org.h2.Driver
    username : sa
    password :
    url : jdbc:h2:mem

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa :
    generate-ddl : true
    hibernate :
      ddl-auto : create-drop
    database : H2
    #show-sql : true

  mail :
    host : smtp.live.com
    port : 587
    username : vteial@hotmail.com
    password : <password>
    #smtp.timeout : 3000
    #smtp.connectiontimeout : 3000
    #smtp.auth : true
    #smtp.starttls.enable : true

  mobile :
    devicedelegatingviewresolver :
      enabled : true

  jackson :
    date-format : dd-MM-yyyy HH:mm:ss

  groovy :
    template :
    #allowRequestOverride : false
    #allowSessionOverride : false
    cache : false
    #contentType : text/html
    #prefix : classpath:/templates/
    #suffix : .tpl
    #templateEncoding : UTF-8
    #template.viewNames :  # whitelist of view names that can be resolved
